version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - ./.env
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-broadcast}
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend-network
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: celery -A config worker -l INFO --concurrency=2
    volumes:
      - media_volume:/app/mediafiles
    env_file:
      - ./.env
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-broadcast}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - db
    networks:
      - backend-network
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: celery -A config beat -l INFO
    env_file:
      - ./.env
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-broadcast}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - db
    networks:
      - backend-network
    restart: unless-stopped

  # Optional Nginx service for static files and reverse proxy
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
    depends_on:
      - web
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend-network:
    driver: bridge
