// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xegnaqsqibkuugxneykd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZ25hcXNxaWJrdXVneG5leWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTc4MjksImV4cCI6MjA2OTI3MzgyOX0.XvBmGlcrJ2xCnRrSstvOmG0RP9TU-N8QhdvuWz3gIFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});